### ISSUE TITLE
Fails to find <svg> child of <div>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/wicked-good-xpath#15]
```
To reproduce:

1. Open a document with wgxpath loaded and a <div> containing an <svg>
2. wgxpath.install()
3. document.evaluate('//div/svg',document.body).iterateNext()

Expectation: an <svg> element is returned

Result: null is returned

Revision: 21 

It seems to be just the child axis which is failing; using the xpath expression 
'//div//svg', the expected <svg> element is returned, yet no amount of wildcard 
children added ('//div/*/svg', '//div/*/*/svg', etc) produce the same result.
```

Original issue reported on code.google.com by `qstr...@gmail.com` on 6 Aug 2014 at 3:08

**Comment by qstrahl** [comment]
Howdy, I'm still suffering from this issue. I see there's some activity what with this project moving to GitHub, so I'd be much obliged if someone could take a second look at it.

**Comment by nedjs** [comment]
@qstrahl Probably a bit late but here it is.

The issue you identified is caused because the `svg` element isnt under the same namespace which most other html elements are. SVG elements are created under the `http://www.w3.org/2000/svg` namespace URI. This particular parser defaults to the `http://www.w3.org/1999/xhtml` if no prefix is defined.

To make your code work you need to define a namespace resolver which is the 3rd argument in the [`document.evaluate` method](https://developer.mozilla.org/en-US/docs/Web/API/Document/evaluate)

Heres what your code should look like:

```javascript
var namespaceResolver = function(prefix) {
    if(prefix === 'svg') {
        return 'http://www.w3.org/2000/svg';
    }
    return 'http://www.w3.org/1999/xhtml';
}
document.evaluate('//div/svg:svg', document.body, namespaceResolver);
```

I just tested this code using your example and was able to get a result.

**Comment by Dominator008** [comment]
Thanks @nedjs.
