### ISSUE TITLE
TypeError: 'localName' is null or not an object

### ISSUE THREAD

**Issue by joshbruning** [google/wicked-good-xpath#36]
https://github.com/google/wicked-good-xpath/commit/98e8b0e43948c5659ab0dcf94b9cea94e2b5a50d breaks compatibility with IE8.

Errors look like this:
TypeError: 'localName' is null or not an object

**Comment by Dominator008** [comment]
Sorry for the breakage. It should be fixed now. The problem is that it's hard to run the unit tests and integration tests in the open source repository (#20). I'm considering using Bazel's Closure Rules (https://github.com/bazelbuild/rules_closure) to at least run them, but I don't have time for that now.
